### ISSUE TITLE
Error on worker #1: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by androidseb25** [lingualogic/speech-angular#1]
Hallo,

ich hab folgendes Problem, wenn ich ein `ng serve` nach der Installation von speech-angular & dem framework tätige, bekommen ich einen `Error on worker #1: RangeError: Maximum call stack size exceeded` Fehler. Was mache ich falsch bzw. wie kann ich den Fehler fixen?

Anbei meine Angular Version und der komplette errorlog

```
Angular CLI: 12.0.3
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.3
@angular-devkit/build-angular   12.0.3
@angular-devkit/core            12.0.3
@angular-devkit/schematics      12.0.3
@schematics/angular             12.0.3
rxjs                            6.6.7
typescript                      4.2.4
```

und hier der komplette Fehlerlog

```
PS X:\PATH-APP> ng serve
⠋ Generating browser application bundles (phase: setup)...Compiling speech-angular : main as commonjs
Error: Error on worker #1: RangeError: Maximum call stack size exceeded
    at resolveNameHelper (X:\PATH-APP\node_modules\typescript\lib\typescript.js:45305:35)
    at resolveName (X:\PATH-APP\node_modules\typescript\lib\typescript.js:45303:20)
    at resolveEntityName (X:\PATH-APP\node_modules\typescript\lib\typescript.js:46585:42)
    at getSymbolOfNameOrPropertyAccessExpression (X:\PATH-APP\node_modules\typescript\lib\typescript.js:78611:28)
    at getSymbolAtLocation (X:\PATH-APP\node_modules\typescript\lib\typescript.js:78680:28)
    at Object.getSymbolAtLocation (X:\PATH-APP\node_modules\typescript\lib\typescript.js:44145:31)
    at Object.findRequireCallReference (X:\PATH-APP\node_modules\@angular\compiler-cli\ngcc\src\host\commonjs_umd_utils.js:41:30)
    at CommonJsReflectionHost.getCommonJsModuleDeclaration (X:\PATH-APP\node_modules\@angular\compiler-cli\ngcc\src\host\commonjs_host.js:214:52)   
    at CommonJsReflectionHost.getDeclarationOfIdentifier (X:\PATH-APP\node_modules\@angular\compiler-cli\ngcc\src\host\commonjs_host.js:47:25)      
    at CommonJsReflectionHost.Esm2015ReflectionHost.getDeclarationOfExpression (X:\PATH-APP\node_modules\@angular\compiler-cli\ngcc\src\host\esm2015_host.js:1795:38)
    at ClusterMaster.onWorkerMessage (X:\PATH-APP\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:195:27)
    at X:\PATH-APP\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:55:95
    at ClusterMaster.<anonymous> (X:\PATH-APP\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:293:57)
    at step (X:\PATH-APP\node_modules\tslib\tslib.js:143:27)
    at Object.next (X:\PATH-APP\node_modules\tslib\tslib.js:124:57)
    at X:\PATH-APP\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (X:\PATH-APP\node_modules\tslib\tslib.js:113:16)
    at EventEmitter.<anonymous> (X:\PATH-APP\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:287:32)
    at EventEmitter.emit (events.js:376:20)
X:\PATH-APP\node_modules\@ngtools\webpack\src\ngcc_processor.js:129
            throw new Error(errorMessage + `NGCC failed${errorMessage ? ', see above' : ''}.`);
            ^

Error: NGCC failed.
    at NgccProcessor.process (X:\PATH-APP\node_modules\@ngtools\webpack\src\ngcc_processor.js:129:19)
    at X:\PATH-APP\node_modules\@ngtools\webpack\src\ivy\plugin.js:110:27
    at Hook.eval [as call] (eval at create (X:\PATH-APP\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:20:1)
    at Hook.CALL_DELEGATE [as _call] (X:\PATH-APP\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (X:\PATH-APP\node_modules\webpack\lib\Compiler.js:1033:30)
    at X:\PATH-APP\node_modules\webpack\lib\Compiler.js:1076:29
    at Hook.eval [as callAsync] (eval at create (X:\PATH-APP\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (X:\PATH-APP\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.compile (X:\PATH-APP\node_modules\webpack\lib\Compiler.js:1071:28)
    at X:\PATH-APP\node_modules\webpack\lib\Watching.js:188:19
```

**Comment by lingualogic** [comment]
Hallo, 
die Speech-Angular 0.5.22 Version war für Angular 7 - 8 ausgelegt. Ob es mit Angular 12 läuft, teste ich jetzt mal. 
Die neue Version 0.6 des Speech-Frameworks ist  als speech Monorepo erstellt und hat keine direkten Abhängigkeiten mehr zu einer bestimmten Angular-Version. Ist aber erst eine Alpha Version und noch nicht für den produktiven Einsatz geeignet.

**Comment by lingualogic** [comment]
Es wurde ein Patch speech-angular12-0.5.2.tgz in den letzten Release eingefügt. Damit kann Speech-Angular mit Angular 12 verwendet werden. Später folgt ein neuer Release 0.5.23, der die Aktualisierung auf Angular 12 als durchgetestete Version liefert.

**Comment by androidseb25** [comment]
Danke der Patch funktioniert 1a
